language: node_js
node_js:
- '8'
install: npm install --no-package-lock --no-shrinkwrap
script:
- npm test
- npm run lint
cache: false
before_install:
- openssl aes-256-cbc -K $encrypted_2cf9f34343d1_key -iv $encrypted_2cf9f34343d1_iv
  -in gcs.json.enc -out gcs.json -d
branches:
  only:
    - master
    - "/^greenkeeper/.*$/"
